- name: Add ansible repository
  become: yes
  apt_repository:
    repo: ppa:ansible/ansible
    state: present

- name: Add bitcoin repository
  become: yes
  apt_repository:
    repo: ppa:bitcoin/bitcoin
    state: present

- name: Remove useless packages from the cache
  become: yes
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes


- name: Create deployment directory
  become: yes
  file: path={{deploy_directory}} state=directory owner=ubuntu group=ubuntu

- name: Make .litecoin conf directories
  file: path=/home/ubuntu/{{item}} state=directory owner=ubuntu group=ubuntu
  with_items:
    - .litecoin

- name: Install app dependencies
  become: yes
  action: apt pkg={{item}} state=installed
  with_items:
    - git
    - build-essential
    - libtool
    - autotools-dev
    - automake
    - libssl-dev
    - libevent-dev
    - bsdmainutils
    - libboost-all-dev
    - python-dev
    - libdb4.8-dev
    - libdb4.8++-dev
    - libzmq3-dev
  tags: package

- name: Install global python requirements
  pip: name={{item}} state=present
  with_items:
    - dpkt
    - gevent
    - ipaddress
    - pygeoip
    - PySocks
    - redis
    - requests

- name: Set authorized keys for ryan
  authorized_key:
    user: ubuntu
    state: present
    key: https://github.com/rromanchuk.keys

- name: "Download latest bitnodes"
  git:
    repo: 'https://github.com/rromanchuk/bitnodes.git'
    dest: /home/ubuntu
    clone: no




