- name: "Add litecored start bash file to work with nvm"
  copy:
    src: start_litecore.sh
    dest: /home/ubuntu/start_litecore.sh
    owner: ubuntu
    group: ubuntu
    mode: 0775

- name: Make .litecoin conf directories
  become: yes
  file: path={{deploy_directory}}/shared/{{item}} state=directory owner=ubuntu group=ubuntu
  with_items:
    - tmp

- name: Copy litecoin service file to systemd services
  become: yes
  template: src=templates/litecoin.service.j2 dest=/lib/systemd/system/litecoin.service

- name: Copy litecore service file to systemd services
  become: yes
  template: src=templates/litecore.service.j2 dest=/lib/systemd/system/litecore.service

- name: Enable litecoin service
  become: yes
  service:
    name: litecoin
    state: started
    enabled: yes

- name: Enable litecore service
  become: yes
  service:
    name: litecore
    state: started
    enabled: yes